In [62]:
import pandas as pd

In [63]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [64]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis = 1, inplace =True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [65]:
df.columns[df.isna().any()]

Index(['Age'], dtype='object')

In [66]:
df['Age'].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [67]:
df['Age'] = df['Age'].fillna(df.Age.mean())
df.head(10)

   Pclass     Sex        Age     Fare  Survived
0       3    male  22.000000   7.2500         0
1       1  female  38.000000  71.2833         1
2       3  female  26.000000   7.9250         1
3       1  female  35.000000  53.1000         1
4       3    male  35.000000   8.0500         0
5       3    male  29.699118   8.4583         0
6       1    male  54.000000  51.8625         0
7       3    male   2.000000  21.0750         0
8       3  female  27.000000  11.1333         1
9       2  female  14.000000  30.0708         1

In [68]:
y = df['Survived']
X = df.drop(['Survived'], axis = 1)
X.head(6)

   Pclass     Sex        Age     Fare
0       3    male  22.000000   7.2500
1       1  female  38.000000  71.2833
2       3  female  26.000000   7.9250
3       1  female  35.000000  53.1000
4       3    male  35.000000   8.0500
5       3    male  29.699118   8.4583

In [69]:
X['Sex'] = X['Sex'].replace({'male':1 , 'female': 0})
X.head()

C:\Users\MSI\AppData\Local\Temp\ipykernel_12484\27448662.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['Sex'] = X['Sex'].replace({'male':1 , 'female': 0})

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [71]:
model.score(X_test, y_test)

0.8268156424581006

In [72]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train, y_train, cv = 5)

array([0.77622378, 0.7972028 , 0.69014085, 0.74647887, 0.78169014])